name = "aiovtue-blog"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "aiovtue-blog"
database_id = "0c103f22-c12a-418b-acda-378db9d1d4f7"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "aiovtue-blog"

[vars]
SITE_URL = "https://x.moci.cc"
ADMIN_USERNAME = "socool"
